# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: mdreader.MDReader
PackageVersion: 0.1.0
InstallerType: nullsoft
Scope: user
UpgradeBehavior: install
ReleaseDate: 2026-09-30
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/tpwatson/md-reader/releases/download/v0.1.0/MD.Reader_0.1.0_x64-setup.exe
    InstallerSha256: 051E14EF1DF19CBCB835810DA1A1E1766C350FC4C378F3267483DD7A441AA2C7
    ProductCode: MD Reader
ManifestType: installer
ManifestVersion: 1.12.0
